### ISSUE TITLE
what is theta_generator role in stage 2?

### ISSUE THREAD

**Issue by shufangxun** [adldotori/ClothFlow#3]
what is theta_generator role in stage 2?  
I think it is a pretrained model. after  it, the processed input  will feed in flownet model.

```
theta_generator = ClothNormalizer(nc=nc)
load_checkpoint(theta_generator, init_CN)

theta = theta_generator(con_cloth_mask, tar_cloth_mask)
grid1 = projection_grid(theta, con_cloth_mask.shape)
grid2 = projection_grid(theta, con_cloth.shape)
con_cloth_mask = Ft.grid_sample(con_cloth_mask, grid1).detach()
con_cloth = Ft.grid_sample(con_cloth, grid2, padding_mode="border").detach()
con_cloth = con_cloth * con_cloth_mask + (1 - con_cloth_mask)

[F, warp_cloth, warp_mask] = model(torch.cat([con_cloth, con_cloth_mask], 1), tar_cloth_mask)
```

**Comment by adldotori** [comment]
Thank you for reading my work. ClothNormalizer resizes cloth original image to person's body size. If use this, the network don't have to reduce clothes' size, so it will be concentrate learning flow. This is an experiment-based opinion. If you have any questions, don't hesitate to ask me. This answer is late, but I will answer the next one right away. I hope this reply was helpful to you.

**Comment by shufangxun** [comment]
thanks~
